export const COUNTRIES = [
    { code: "BR", name: "Brasil", flag: "🇧🇷" },
    { code: "US", name: "Estados Unidos", flag: "🇺🇸" },
    { code: "PT", name: "Portugal", flag: "🇵🇹" },
    { code: "ES", name: "Espanha", flag: "🇪🇸" },
    { code: "FR", name: "França", flag: "🇫🇷" },
    { code: "DE", name: "Alemanha", flag: "🇩🇪" },
    { code: "IT", name: "Itália", flag: "🇮🇹" },
    { code: "GB", name: "Reino Unido", flag: "🇬🇧" },
    { code: "CA", name: "Canadá", flag: "🇨🇦" },
    { code: "AR", name: "Argentina", flag: "🇦🇷" },
    { code: "UY", name: "Uruguai", flag: "🇺🇾" },
    { code: "CL", name: "Chile", flag: "🇨🇱" },
    { code: "CO", name: "Colômbia", flag: "🇨🇴" },
    { code: "PE", name: "Peru", flag: "🇵🇪" },
    { code: "MX", name: "México", flag: "🇲🇽" },
    { code: "JP", name: "Japão", flag: "🇯🇵" },
    { code: "CN", name: "China", flag: "🇨🇳" },
    { code: "AU", name: "Austrália", flag: "🇦🇺" },
    { code: "NZ", name: "Nova Zelândia", flag: "🇳🇿" },
    { code: "AO", name: "Angola", flag: "🇦🇴" },
    { code: "MZ", name: "Moçambique", flag: "🇲🇿" },
    { code: "CV", name: "Cabo Verde", flag: "🇨🇻" },
    { code: "GW", name: "Guiné-Bissau", flag: "🇬🇼" },
    { code: "ST", name: "São Tomé e Príncipe", flag: "🇸🇹" },
    { code: "TL", name: "Timor-Leste", flag: "🇹🇱" },
].sort((a, b) => a.name.localeCompare(b.name));
